Update pipeline01.yml

diff --git a/.github/workflows/pipeline01.yml b/.github/workflows/pipeline01.yml
--- a/.github/workflows/pipeline01.yml
+++ b/.github/workflows/pipeline01.yml
@@ -20,19 +20,19 @@ jobs:
       - name: Checkout for git clone
         uses: actions/checkout@v6.0.1
 
-      - name: Install Azure CLI (if not present)
-        run: |
-          if ! command -v az >/dev/null 2>&1; then
-            echo "Azure CLI not found, installing..."
-            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-          else
-            echo "Azure CLI already installed"
-          fi
+      # - name: Install Azure CLI (if not present)
+      #   run: |
+      #     if ! command -v az >/dev/null 2>&1; then
+      #       echo "Azure CLI not found, installing..."
+      #       curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+      #     else
+      #       echo "Azure CLI already installed"
+      #     fi
 
-      - name: Verify Azure CLI
-        run: |
-          which az
-          az version          
+      # - name: Verify Azure CLI
+      #   run: |
+      #     which az
+      #     az version          
                 
       - name: Azure Login via OIDC
         uses: azure/login@v2
